[title]
en = "Experience"
fr = "Expérience"

[body]
en = """
Throughout my studies, I have had the opportunity to gain experience as a software developer through multiple internships. During these internships, I have developed not only my technical skills, but also my interepersonal skills such as communication and teamwork. All of these have been incredible learning experiences for me and I am looking forward to gain even more experience in future opportunites.

Below you will find information about my internships and other forms of experience as part of a team.
"""
fr = """
Tout au long de mes études, j'ai eu l'opportunité d'acquérir de l'expérience en tant que développeur logiciel grâce à plusieurs stages. Pendant ces stages, j'ai développé non seulement mes compétences techniques, mais aussi mes compétences interpersonnelles telles que la communication et le travail d'équipe. Toutes ces expériences d'apprentissage ont été incroyables pour moi et je suis impatient de gagner encore plus d'expérience dans les opportunités futures.

Ci-dessous vous trouverez plus d'information à propos de mes stages et autres formes d'expérience en tant que membre d'équipes.
"""
