date = { start = 2021-09-01, end = 2025-05-01 }
title = { en = "B.Eng. Software Engineering Co-op", fr = "Génie logiciel co-op (B.Eng.)" }
icon = "McGill_logo.png"

[summary]
en = ".."
fr = ".."

[resume_lines]
en = [
  "CGPA: 3.96/4.0",
  "Selected for the Dean's Honour List for my first and second years.",
  "Recipient of multiple merit-based scholarships, including the Les Vadasz Award in Engineering and the Faculty of Engineering Scholarship.",
]
fr = [
  "Moyenne cumulative: 3.96/4.0",
  "Séléctionné pour la « Dean's Honour List » pour ma première et deuxième année.",
  "Récipiendaire de plusieurs bourses basées sur le mérite académique, dont le « Les Vadasz Award in Engineering » et le « Faculty of Engineering Scholarship ».",
]

[body]
en = """
During my time at McGill, I've had many opportunities to learn and grow. This includes coursework, of course, but also the practical experience and interpersonal skills I've gained while working on team projects.

In my first semester, I enrolled in the McGill Artificial Intelligence Society's "MAIS 202" bootcamp, an accelerated introduction to AI and ML. I later joined McGill's robotics team, and worked on a Mars rover. However, I soon found out that I was more interested in game development, and I joined the GameDev McGill club.

Each semester, I am more experienced than the last and I learn about the inner workings of different areas and technologies. When I look back at my previous work experiences and projects, I am amazed at how far I've come and how much I've learned!
"""
fr = """
Durant mon parcours à McGill, j'ai eu de nombreuses occasions d'apprendre et de grandir. Cela inclut bien sûr les cours, mais aussi l'expérience pratique et les compétences interpersonnelles que j'ai acquises en travaillant sur des projets d'équipe.

Dans mon premier semestre, je me suis inscrit à « MAIS 202 », un cours d'introduction à l'IA et au machine learning offert par la société d'IA de McGill. Plus tard, j'ai joint l'équipe de robotique de McGill et j'ai travaillé sur un rover. Par contre, je me suis rendu compte que j'étais plus intéressé par le développement de jeux vidéos et j'ai alors joint le club GameDev McGill.

Chaque semestre, j'ai plus d'expérience que le précédent et j'acquiers des connaissances au sujet du fonctionnement de différents systèmes et technologies. Quand je regarde mes anciens projets et expériences de travail, je me rends compte de tout ce que j'ai appris!
"""
